### PR TITLE
Gui detailed group view

### LINKED ISSUE #9: Detailed view of a specific group
Accessed through the listener of an item in RecyclerView.

### LINKED ISSUE #11: Create a button for adding more users to group, AFTER creation.

### LINKED ISSUE #14: Allow users to add other users from the contactbook to a group during the user-adding-process.

### PR DESCRIPTION
**Pull request by Puh00**
Implemented:
* GUI of DetailedGroup
* Connected DetailedGroup with PickUserFragment for adding more members.
* ShowmembersFragment (Wating for UserCardViewAdapter)

Closes #9, Closes #11, Closes #14

### CODE REVIEW

**Review by Puh00 — COMMENTED** [review]
Commented sections that need explanation

**Comment by yenanw** [comment]
lgtm

**Review by yenanw — APPROVED** [review]

**Review by gabrielbrattgard — APPROVED** [review]
Looks good.

**Comment by OlofSjogren** [comment]
Bit late, but looks good!

**Pull request merged**
