### PR TITLE
Refactor ModelEngine's Singleton implementation

### PR DESCRIPTION
**Pull request by yenanw**
### What changed
- Introduced a new super class _ModelEngineViewModel_ for all classes in the  _viewmodel_ package
  - _ModelEngineViewModel_ is a subclass of _ViewModel_ and holds a static instance of _ModelEngine_ which can be retrieved by all of its subclasses using getModel() method
- Removed Singleton pattern in _ModelEngine_
  - It now takes in an instance of _IDatabase_ in its constructor
- ~~Combined _Database_ and _MockDatabase_ package into a singular package _database_~~
  - ~~I don't like uppercase so~~
- ~~Introduced a new factory class _ModelDatabaseFactory_ which can create a _ModelEngine_ with either _RealDatabase_ or _MockDatabase_~~
  - ~~Both database classes are now package-private and cannot be accessed in anyway from outside~~

### CODE REVIEW

**Comment by yenanw** [comment]
PepePls

**Review by Puh00 — APPROVED** [review]
Here's your sandwich

"_removed image because it was too big_" - me

**Review by OscarSanner — CHANGES_REQUESTED** [review]
This is going to fail the tests, or rather, the tests wont even build. Can you 

- Pull master 
- Set the modelEngine variable in ModelEngine test

Would be appreciated. Should pass from then. (if the code is good)

**Review by OlofSjogren — APPROVED** [review]

**Review by OscarSanner — APPROVED** [review]
This is really nice!

**Pull request merged**
