### PR TITLE
Model facade feature

### LINKED ISSUE #13: Create ModelEngine class with relevant functions and instance variables according to specified UML.

### LINKED ISSUE #15: Implement Singleton Pattern on ModelEngine

### PR DESCRIPTION
**Pull request by OscarSanner**
closes #13 
closes #15 

opened as opened pullrequest and should not be merged until the pull request is marked as ready

### CODE REVIEW

**Comment by OscarSanner** [comment]
@Puh00 @OlofSjogren This will be further worked on as soon as the Account class is up and running, as this is a facade class it will depend on several other classes

**Comment by OscarSanner** [comment]
@Puh00 on it.

**Comment by Puh00** [comment]
@OscarSanner TemplateClass.java should probably be removed in its entirety.

**Comment by OscarSanner** [comment]
Seems to be removed in masterbranch @Puh00

**Pull request merged**
